# CSKoth configuration file

# Default capture time in seconds
default-capture-time: 300

# Default points awarded for capturing
default-capture-points: 1

# List of rewards commands to execute when a player captures the KOTH
# %player% - The player who captured the KOTH
# %koth% - The name of the KOTH
rewards:
  - "broadcast &a%player% has captured the %koth% KOTH!"
  - "give %player% diamond 5"

# Debug mode for additional logging
debug: false